# version: '2.38.2'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:   #tableplus çalıssın diye ekledim.
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api-1:
    build: .
    container_name: api-1
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskmanager
      JWT_SECRET: supersecretkey123
      JWT_EXPIRES_IN: 7d
      INSTANCE_ID: api-1
    depends_on:
      - postgres
    networks:
      - app-network

  api-2:
    build: .
    container_name: api-2
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskmanager
      JWT_SECRET: supersecretkey123
      JWT_EXPIRES_IN: 7d
      INSTANCE_ID: api-2
    depends_on:
      - postgres
    networks:
      - app-network

  api-3:
    build: .
    container_name: api-3
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskmanager
      JWT_SECRET: supersecretkey123
      JWT_EXPIRES_IN: 7d
      INSTANCE_ID: api-3
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-1
      - api-2
      - api-3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: